[project]
name = "speedagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-ai>=1.61.0",
    "openai>=1.0.0",
    "langchain-experimental>=0.4.1",
    "python-dotenv>=1.0.0",
    "geometric>=1.1",
    "matplotlib>=3.10.8",
    "mdtraj",
    "numpy",
    "openmm>=8.4.0.post2",
    "pandas>=3.0.1",
    "parmed",
    "pyscf>=2.5.0",
    "pytest>=9.0.2",
    "rdkit>=2025.9.5",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.0",
    "seaborn>=0.13.2",
]
